# Generated by Django 3.2.1 on 2021-05-05 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 5, 15, 54, 49, 449197))),
                ('Comment', models.TextField()),
                ('media', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
