# Generated by Django 3.2.1 on 2021-05-05 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyentry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 5, 18, 30, 9, 524020)),
        ),
        migrations.AlterField(
            model_name='surveyentry',
            name='media',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
    ]
