# Generated by Django 3.2.1 on 2021-05-05 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_details', '0002_auto_20210505_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyentry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 5, 22, 22, 10, 810009)),
        ),
    ]
