# Generated by Django 3.2.1 on 2021-05-05 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_details', '0003_alter_surveyentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyentry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 5, 23, 6, 39, 3345)),
        ),
        migrations.AlterField(
            model_name='surveyentry',
            name='media',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
