# Generated by Django 3.0.5 on 2021-05-06 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_details', '0004_auto_20210505_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyentry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 6, 14, 56, 33, 746244)),
        ),
        migrations.AlterField(
            model_name='surveyentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
